### ISSUE TITLE
Is fo:table supported?

### ISSUE THREAD

**Issue by AlexSchuetz** [cajuncoding/PdfTemplating.XslFO#5]
Hi,
I am migrating an existing report to c#. Inside our FO-File we are using fo:table and corresponding tags.
Unfortunatly I cannot see the table in the resulting pdf.

Are Tables just not supported?

(I am using the exact same files with java as well and the table is rendered.)

**Comment by AlexSchuetz** [comment]
I just found an old issue inside FO.Net: [The PDF file generated doesn't have the FO-table contents](https://archive.codeplex.com/?p=fonet#).
So probably this is the problem and tables are not fully supported at the moment.

If I add the optional `<fo:table-column column-width="proportional-column-width(20)"/> ` the table is rendered.

**Comment by cajuncoding** [comment]
Yes you definitely can't compare the old .Net port to newer Java Apache FOP at all...many things evolved so various elements may have slightly different syntax or not be supported.

But with that said Tables in general most definitely work in FO.Net, otherwise basic layout control wouldn't exist and I've used them for some layouts that I definitely would not classify as basic.

As you noted you may have to provide at least one width value, or something but they do work. I seem to recall having a similar experience years back but then just got into a habit of using my Xslt libraries and it was handled.

One thing I've done in my sample projects is have template variable that tells my templates if they should render for ApacheFOP or FO.Net, so they could handle the differences...this worked well in my ApacheFOP.Serverless example branch.
